--貯金箱--
INSERT INTO SAVINGS_BOX (ID, TOTAL_AMOUNT, USER_ID) VALUES (10, 1000.0, 10);
INSERT INTO SAVINGS_BOX (ID, TOTAL_AMOUNT, USER_ID) VALUES (12, 1000.0, 12);
INSERT INTO SAVINGS_BOX (ID, TOTAL_AMOUNT, USER_ID) VALUES (13, 1000.0, 13);

-- Inserting test data into the UserAccount table
INSERT INTO USER_ACCOUNT (id, username, password, SAVINGS_BOX_ID) VALUES (10, 'xiaoLiu', 'srsr1027',10);
INSERT INTO USER_ACCOUNT (id, username, password, SAVINGS_BOX_ID) VALUES (12, 'jane_smith', 'passw0rd', 12);
INSERT INTO USER_ACCOUNT (id, username, password, SAVINGS_BOX_ID) VALUES (13, 'alice_jones', 'alicepass', 13);

-- Assuming UserAccount IDs 1, 2, and 3 already exist in the UserAccount table

INSERT INTO WISH_ITEM (NAME, CURRENT_AMOUNT, NEEDED_AMOUNT, USER_ACCOUNT_ID) VALUES ('Vacation Fund', 500.00, 3000.00, 1);
INSERT INTO WISH_ITEM (NAME, CURRENT_AMOUNT, NEEDED_AMOUNT, USER_ACCOUNT_ID) VALUES ('New Car', 1500.00, 15000.00, 1);
INSERT INTO WISH_ITEM (NAME, CURRENT_AMOUNT, NEEDED_AMOUNT, USER_ACCOUNT_ID) VALUES ('Emergency Fund', 2000.00, 10000.00, 1);

--MySavingRule--
INSERT INTO MY_SAVING_RULE (AMOUNT, ID, USER_ID, DESCRIPTION, TITLE) VALUES
(5000, 5, 1, '仕事終わりの余計な買い食いをしない', '月次貯金'),
(3000, 2, 1, '弁当を作る', '旅行貯金'),
(10000, 3, 1, '外食をしない', 'ガジェット貯金');

-- 月次貯金: 月曜と金曜に適用
INSERT INTO MY_SAVING_RULE_FREQUENCY (MY_SAVING_RULE_ID, DAY_OF_WEEK) VALUES
(5, 'MONDAY'),
(5, 'FRIDAY');

-- 旅行貯金: 水曜と土曜に適用
INSERT INTO MY_SAVING_RULE_FREQUENCY (MY_SAVING_RULE_ID, DAY_OF_WEEK) VALUES
(2, 'WEDNESDAY'),
(2, 'SATURDAY');

-- ガジェット貯金: 火曜と木曜に適用
INSERT INTO MY_SAVING_RULE_FREQUENCY (MY_SAVING_RULE_ID, DAY_OF_WEEK) VALUES
(3, 'TUESDAY'),
(3, 'THURSDAY');


